GET http://localhost:1122/make

GET http://localhost:1122/term/89/11

GET http://localhost:9090/fetch

POST http://localhost:9090/new
content-type: application/json

{
    "acc_number":3333,
    "acc_bal":8992.4,
    "acc_holder":"Hameed"
}